---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    prometheus.io/scrape: "true"
    fabric8.io/scm-tag: HEAD
    prometheus.io/port: "9779"
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/online-store-web
  labels:
    expose: "true"
    app: online-store-web
    provider: fabric8
    #version: 0.0.1-SNAPSHOT
    group: org.springframework.boot
  name: online-store-web
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: online-store-web
    provider: fabric8
    group: org.springframework.boot
